# Generated by Django 6.0.2 on 2026-02-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PG', 'W trakcie'), ('CP', 'Zakończono (zebrano)'), ('CL', 'Anulowano (nie przetrwaly)')], default='PG', max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.croptype')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.field')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
