# Generated by Django 6.0.2 on 2026-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_croptype_created_croptype_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='cultivation',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
    ]
