# Generated by Django 6.0.2 on 2026-02-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_cultivation_notes_cultivation_slug_field_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivation',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
