# Generated by Django 6.0.2 on 2026-02-23 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_alter_cultivation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivation',
            name='crop_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivations', to='crops.croptype'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivations', to='crops.field'),
        ),
    ]
