# Generated by Django 6.0.2 on 2026-02-24 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_alter_cultivation_crop_type_alter_cultivation_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cultivation',
            name='yield_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Plony (w tonach)'),
        ),
    ]
