# Generated by Django 6.0.2 on 2026-02-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_cultivation_owner_cultivation_yield_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivation',
            name='yield_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Plony (w kg)'),
        ),
    ]
