# Generated by Django 6.0.2 on 2026-02-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0008_alter_cultivation_yield_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='soil_class',
            field=models.TextField(choices=[('I', 'I klasa'), ('II', 'II klasa'), ('III', 'III klasa'), ('IV', 'IV klasa'), ('V', 'V klasa'), ('VI', 'VI klasa')], default='V'),
        ),
    ]
