# Generated by Django 6.0.2 on 2026-02-24 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0009_field_soil_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivation',
            name='sowing_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
