# Generated by Django 6.0.2 on 2026-02-25 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0010_cultivation_sowing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='description',
            new_name='note',
        ),
    ]
