# Generated by Django 6.0.2 on 2026-02-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0011_rename_description_field_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='note',
            new_name='notes',
        ),
    ]
