# Generated by Django 6.0.2 on 2026-02-25 00:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0012_rename_note_field_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.TextField(choices=[('SW', 'Siew'), ('FT', 'Nawożenie'), ('PT', 'Ochrona roślin'), ('HV', 'Zbiór'), ('PL', 'Orka'), ('HR', 'Bronowanie'), ('CT', 'Gruberowanie'), ('DC', 'Talerzowanie'), ('OT', 'Inna czynność')], default='OT')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Data wykonanie')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='crops.field')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
