# Generated by Django 6.0.2 on 2026-02-25 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0013_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='crop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.croptype', verbose_name='Roślina uprawna (tylko przy siewie)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='soil_class',
            field=models.CharField(choices=[('I', 'I klasa'), ('II', 'II klasa'), ('III', 'III klasa'), ('IV', 'IV klasa'), ('V', 'V klasa'), ('VI', 'VI klasa')], default='V'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='crops.field'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('SW', 'Siew'), ('FT', 'Nawożenie'), ('PT', 'Ochrona roślin'), ('HV', 'Zbiór'), ('PL', 'Orka'), ('HR', 'Bronowanie'), ('CT', 'Gruberowanie'), ('DC', 'Talerzowanie'), ('OT', 'Inna czynność')], default='OT', max_length=2),
        ),
    ]
