# Generated by Django 6.0.2 on 2026-02-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0014_treatment_crop_type_alter_field_soil_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='crop_type',
            field=models.ForeignKey(blank=True, help_text='Wymagane tyklo dla zbiegu typu siew', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.croptype', verbose_name='Roślina uprawna'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('SW', 'Siew'), ('FT', 'Nawożenie'), ('LM', 'Wapnowanie'), ('PT', 'Ochrona roślin'), ('HV', 'Zbiór'), ('PL', 'Orka'), ('HR', 'Bronowanie'), ('CT', 'Gruberowanie'), ('DC', 'Talerzowanie'), ('OT', 'Inna czynność')], default='OT', max_length=2),
        ),
    ]
